name: MultasPlugin
main: com.tuplugin.multas.MultasPlugin
version: 1.0.0
api-version: 1.21
authors: ["TuNombre"]
commands:
  multa:
    description: Crear o gestionar multas
    usage: /multa <jugador> <dinero> <razon>
    permission: multas.use
    permission-message: "No tienes permiso para usar /multa"
